### PR TITLE
Hfeyp 446, 458, 513 - A/B Testing LandingPage & FeaturedPages

### PR DESCRIPTION
**Pull request by tunde-anddigital**
### Context
[Hfeyp 446](https://dfedigital.atlassian.net/jira/software/projects/HFEYP/boards/83?selectedIssue=HFEYP-446)
[Hfeyp 458](https://dfedigital.atlassian.net/jira/software/projects/HFEYP/boards/83?selectedIssue=HFEYP-458)
[Hfeyp 513](https://dfedigital.atlassian.net/jira/software/projects/HFEYP/boards/83?selectedIssue=HFEYP-513)

### Changes proposed in this pull request
- Add index page (landing page) variants

(index.html) (Original page)
- No changes (apart from adding the safeguarding section)

(index_v1.html) (Design 1)
- Add safeguarding section to landing page
- Change both sections to match card layout style - Get Help and Safeguarding
- Add overview link cards for featured pages

(Index_v2.html) (Design 2)
- Add safeguarding section to landing page below Get Help section
- Extend grey background to cover featured page sections as well

### Guidance to review
- Check index page variants match designs in ticket [517](https://dfedigital.atlassian.net/jira/software/projects/HFEYP/boards/83?selectedIssue=HFEYP-517)

### CODE REVIEW

**Review by ebrett — CHANGES_REQUESTED** [review]
As I discovered when deploying the content blocks in production, we can't actually run `db:seed` in production, as it is destructive.  We need a standalone task to add new pages to the database, or instructions on how to do it from the console (which is how I ended up doing for content blocks).

**Comment by ebrett** [comment]
Also, is the adding of the safeguarding section to the "original" landing page not done here?  I only see the variant landing pages

**Review by guy-roberts — COMMENTED** [review]
For the featured pages, I was thinking of adding an extra attribute called ‘featured’ to the ContentPage model.

Instead of hard coding their titles

Was also thinking of adding a PageCategory model and a category id to the ContentPage. To group them

**Comment by tunde-anddigital** [comment]
> Also, is the adding of the safeguarding section to the "original" landing page not done here? I only see the variant landing pages

There's a partial in index.html (original) (_show_links_to_children_of_page_with_title.html) which originally just renders the Get help section. This was modified to render the safeguarding section too, so no changes needed to be made to the index.html file

**Comment by ebrett** [comment]
> > Also, is the adding of the safeguarding section to the "original" landing page not done here? I only see the variant landing pages
> 
> There's a partial in index.html (original) (_show_links_to_children_of_page_with_title.html) which originally just renders the Get help section. This was modified to render the safeguarding section too, so no changes needed to be made to the index.html file

Ah, I can see that now - thanks!

**Review by ebrett — DISMISSED** [review]
I'm approving, but I also made the changes, so helpful to have @tunde-anddigital and @guy-roberts take a look and approve or not

**Review by guy-roberts — APPROVED** [review]
Looks good to me

**Comment by ebrett** [comment]
Note here that once deployed two task should be run:

`rails load:safeguarding`
and
`rails load:blocks`

**Pull request merged**
