### PR TITLE
docker related seed

### PR DESCRIPTION
**Pull request by dmallett1**

### CODE REVIEW

**Review by guy-roberts — COMMENTED** [review]
I guess there is one way to find out, by deploying it to the test env

**Review by dmallett1 — COMMENTED** [review]
I think I should have left db:prepare in

**Review by guy-roberts — APPROVED** [review]

**Comment by dmallett1** [comment]
Merge

**Comment by ebrett** [comment]
Sorry, just getting to this now -- I think the entry points are only used for `docker-compose` which is only used for local development, not for cloud foundry / terraform deployment

**Comment by dmallett1** [comment]
Actually there were 3 seed points and the docker_entry.sh change has stopped deployments running seeds to test env.

The problem is deployment.yml runs docker which runs docker_entry.sh (the offending script) for the Test env.  There is also an app.json in addition to the variables.tf

**Pull request merged**
